-- English word set for Wordladder (3-5 letters): existing curated 3-letter common words +
-- anagram.koplugin's frequency-filtered 4-5 letter words (Google Books top-N ∩ dwyl dictionary).
local W = {}
local raw = [[
aaron,abba,abbey,abby,abide,abit,able,abode,abort,about,above,abuse,acad,acct,ace,acer,aces,ache,acid,acids
aclu,acme,acne,acorn,acre,acres,act,acta,acted,actor,acts,acute,adam,adams,adapt,add,added,addr,adds,admin
admit,adobe,adopt,adult,aero,afro,after,again,age,aged,agent,ages,agile,aging,agnes,ago,agree,ahead,ahmed,aid
aide,aided,aides,aids,aim,aimed,aims,air,aired,aisle,ajax,akin,akron,alain,alamo,alan,alarm,alas,alba,album
alec,alert,alex,alfa,algae,alias,alice,alien,align,alike,alive,all,allah,allan,allay,alle,allen,alley,allot,allow
alloy,ally,alma,aloe,aloha,alone,along,aloud,alpha,alps,also,altar,alter,alto,alvin,amber,amen,amend,amex,amid
amiga,amino,ammo,among,amor,amos,ample,amps,anal,and,andre,andy,angel,anger,angie,angle,anglo,angry,angus,anime
anita,ankle,anna,anne,annex,annie,annum,anon,ansi,ant,ante,anti,anton,ants,any,apart,apex,apis,appl,apple
apply,april,apron,apt,aqua,arab,arabs,arbor,arc,arch,are,area,areas,arena,ares,argos,argue,argus,aria,arid
ariel,aries,arise,ark,arm,armed,armor,arms,army,aroma,arose,array,arrow,art,arte,arts,asap,ascii,ashes,asia
asian,aside,ask,asked,asks,aspen,assay,asses,asset,assoc,asst,ate,atlas,atom,atoms,attic,attn,audio,audit,aunt
aura,auth,auto,autos,avail,avant,avery,avian,avid,avis,avoid,await,awake,award,aware,away,awe,awful,axe,axel
axes,axial,axis,axle,aye,babe,babes,baby,bach,back,backs,bacon,bad,badge,badly,bag,bags,baht,bail,bait
baja,bake,baked,baker,bald,bale,bali,ball,balls,balm,ban,band,bands,bane,banff,bang,banjo,bank,banks,bans
bar,barb,bard,bare,bark,barn,baron,barr,barre,barry,bars,bart,basal,base,based,bases,bash,basic,basil,basin
basis,bask,bass,bat,batch,bates,bath,baths,baton,bats,bay,bays,beach,bead,beads,beam,beams,bean,beans,bear
beard,bears,beast,beat,beats,beau,beck,becky,bed,beds,beech,beef,been,beer,beers,bees,beet,beg,began,begin
begun,beige,being,bell,bella,belle,bells,belly,below,belt,belts,bench,bend,benin,benny,bent,berg,bern,berry,bert
best,bet,beta,beth,bets,betsy,betty,bezel,bias,bible,bid,bids,bien,big,bike,biker,bikes,bile,bill,bills
billy,bind,binds,bingo,bins,biol,bios,birch,bird,birds,birth,bison,bit,bitch,bite,bites,bits,blab,black,blade
blah,blair,blake,blam,blame,blanc,bland,blank,blast,blaze,bldg,bleed,blend,bless,blew,blind,blink,bliss,blitz,blob
bloc,block,blond,blood,bloom,blow,blown,blows,blue,blues,bluff,blunt,blur,blush,blvd,board,boat,boats,bobby,boca
body,bogus,boil,boing,boise,bold,bolt,bolts,bomb,bombs,bond,bonds,bone,bones,bono,bonus,boob,boobs,book,books
bool,boom,boone,boost,boot,booth,boots,booty,bore,bored,boris,born,borne,bosch,bose,boss,both,bots,bound,bout
bowel,bowie,bowl,bowls,bows,box,boxed,boxer,boxes,boy,boyd,boys,brace,brad,brag,brain,brake,brand,bras,brass
brave,bravo,bray,bread,break,bred,breed,brent,brett,brew,brian,brick,bride,brief,brim,bring,brit,broad,brock,broke
bronx,brook,bros,brow,brown,bruce,bruno,brush,bryan,bryce,buck,bucks,bud,buddy,buds,buff,buffy,bug,buggy,bugs
buick,build,built,bulb,bulbs,bulk,bull,bulls,bump,bun,bunch,bunk,bunny,burke,burma,burn,burns,burnt,burp,burr
burst,burt,bury,bus,buses,bush,bust,busty,busy,but,butt,butte,butts,buy,buyer,buys,buzz,byron,byte,bytes
cab,cabin,cable,cache,cadet,cafe,cafes,cage,cages,cain,cairo,cajun,cake,cakes,calc,calf,call,calls,calm,came
camel,camp,camps,cams,can,canal,candy,cane,canoe,canon,cans,cant,cap,cape,capri,caps,car,carat,card,cards
care,cared,cares,carey,cargo,carl,carlo,carol,carp,carr,carry,cars,cart,carte,carts,cary,casa,case,cases,casey
cash,cass,cast,casts,cat,catch,cater,cathy,cats,cause,cave,caves,cease,cecil,cedar,celeb,cell,cello,cells,cent
cents,cern,cert,cest,chad,chain,chair,chalk,champ,chan,chang,chaos,chap,char,charm,chars,chart,chase,chat,chats
cheap,cheat,check,cheek,cheer,chef,chefs,chem,chen,cheng,cher,chess,chest,chevy,chew,chic,chick,chico,chief,child
chile,chili,chill,chin,china,ching,chip,chips,chit,chloe,choir,chop,chord,chose,chow,chris,chub,chuck,chung,chunk
ciao,cider,cigar,cindy,circa,cisco,cite,cited,cites,city,civic,civil,clad,claim,clair,clam,clamp,clan,clap,clara
clare,clark,clash,class,claus,claw,clay,clean,clear,clerk,click,cliff,climb,clin,clint,clip,clips,clit,clive,clock
clod,clog,clone,clop,close,cloth,cloud,clown,club,clubs,clue,clues,clyde,coach,coal,coast,coat,coats,cob,cobb
cobra,coca,cock,cocks,coco,cocoa,cocos,cod,code,codec,coded,codes,coed,cog,cohen,coil,coin,coins,coke,cola
cold,cole,coli,colin,coll,colon,color,colt,colts,coma,comb,combo,come,comes,comet,comic,comm,comma,comp,cond
condo,cone,conf,congo,conn,cons,const,cont,cook,cooks,cool,coop,cop,cope,cops,copy,coral,cord,cords,core
cores,corey,cork,corn,corp,corps,corr,cory,cost,costa,costs,cot,cote,couch,cough,could,count,coup,coupe,court
cove,cover,cow,cows,cozy,cpus,crab,crack,craft,craig,cram,crane,crank,crap,craps,crash,crate,crawl,crazy,cream
creed,creek,creep,creme,crest,crete,crew,crews,crib,cried,cries,crime,crisp,crop,crops,cross,crow,crowd,crown,crude
cruel,crush,crust,cry,crypt,ctrl,cub,cuba,cuban,cube,cubes,cubic,cubs,cues,cuff,cult,cunt,cup,cups,curb
cure,cured,curl,curly,curry,curse,curt,curve,cut,cute,cutie,cuts,cyan,cyber,cycle,cyrus,czech,dab,dad,daddy
dade,dads,daily,dairy,daisy,dale,dam,dame,damn,damon,damp,dams,dana,dance,dane,danny,dansk,dante,darby,dare
dark,darn,dart,darts,dash,data,date,dated,dates,datum,dave,david,davis,dawn,days,dead,deaf,deal,deals,dealt
dean,dear,death,debit,debt,debts,debug,debut,decal,decay,deck,decks,deco,decor,deed,deeds,deep,deer,delay,delhi
deli,dell,della,delta,demi,demo,demon,demos,denim,denis,dense,dent,deny,depot,dept,depth,derby,derek,desc,desk
desks,deter,devel,devil,devon,dewey,dial,diana,diane,diary,dice,dick,dicks,didnt,died,diego,dies,diet,diets,diff
digit,dike,dildo,dill,dime,dinar,dine,diner,ding,dino,diode,dion,dip,dire,dirk,dirt,dirty,disc,disco,discs
dish,disk,disks,dist,ditch,diva,dive,diver,dixie,dock,docs,dodge,does,doff,dog,dogs,doing,dolce,dole,doll
dolls,dolly,dome,done,dong,donna,donor,dont,doom,door,doors,dora,doris,dorm,dose,doses,dot,dote,dots,doubt
doug,dough,dove,dover,down,downs,doyle,dozen,drab,draft,drag,drain,drake,dram,drama,drank,draw,drawn,draws,dread
dream,dress,drew,dried,drift,drill,drink,drip,drive,drone,drop,drops,drove,drown,drug,drugs,drum,drums,drunk,dry
dryer,dual,duane,dub,duck,ducks,duct,dude,duel,dues,duff,dug,duke,dukes,dull,duly,dumb,dummy,dump,dun
dune,dunes,dung,dunno,dusk,dust,dusty,dutch,duty,dwarf,dwell,dyer,dyes,dying,dyke,dylan,each,eager,eagle,ear
earl,early,earn,earns,ears,earth,ease,east,easy,eat,eaten,eater,eats,ebony,echo,econ,eddie,eddy,eden,edgar
edge,edges,edit,edith,edits,educ,edwin,egg,eggs,ego,egypt,eight,elbow,elder,elec,elect,elem,elf,eliot,elite
eliza,ella,elle,ellen,elm,else,elvis,email,ember,emily,emit,emma,emory,empty,emule,end,ended,ends,enemy,engl
enjoy,enter,entre,entry,envy,epic,epoch,epoxy,equal,equip,era,erase,erect,eric,erica,erie,erik,erin,ernie,ernst
error,essay,essex,ethan,ether,euro,euros,evade,eval,evan,evans,eve,even,event,ever,every,evil,evite,ewe,exact
exalt,exam,exams,excel,excl,exec,exile,exist,exit,exits,expo,extra,eye,eyed,eyes,ezra,fable,face,faced,faces
fact,facts,fad,fade,faded,fail,fails,faint,fair,faire,fairs,fairy,faith,fake,fakes,fall,falls,false,fame,fan
fancy,fang,fans,fare,fares,farm,farms,fast,fat,fatal,fate,fats,fatty,fault,fauna,faux,favor,fawn,faxes,faze
fear,fears,feast,feat,fee,feed,feeds,feel,feels,fees,feet,felix,fell,felt,femme,fence,fend,feral,fern,ferry
fest,fetal,fetch,fete,fetus,fever,few,fewer,fiat,fiber,fibre,field,fiery,fife,fifth,fifty,fig,fight,figs,fiji
file,filed,files,fill,fills,film,films,filth,fin,final,finch,find,finds,fine,fined,fines,finn,fins,fire,fired
fires,firm,firms,first,fish,fist,fit,fits,five,fix,fixed,fixes,flag,flags,flair,flame,flap,flare,flash,flask
flat,flats,flaw,flaws,flea,fled,flee,fleet,flesh,flew,flex,flick,flies,flint,flip,flirt,float,flock,flog,flood
floor,flop,flora,flour,flow,flown,flows,floyd,fluid,flush,flute,flux,fly,flyer,foam,focal,focus,foe,fog,foil
fold,folds,folio,folk,folks,fond,font,fonts,food,foods,fool,fools,foot,for,force,ford,fore,forex,forge,fork
forks,form,forma,forms,fort,forte,forth,forty,forum,foul,found,four,fowl,fox,frame,franc,frank,franz,frau,fraud
freak,fred,free,freed,freq,fresh,frey,fried,fries,fritz,frog,frogs,from,front,frost,fruit,fry,fuck,fucks,fudge
fuel,fuels,fuji,full,fully,fun,fund,funds,fungi,funk,funky,funny,fur,furry,fury,fuse,fuzz,fuzzy,gabon,gag
gage,gail,gain,gains,gala,gale,gall,gals,game,gamer,games,gamma,gang,gangs,gap,gape,gaps,garb,garde,garth
gary,gas,gases,gash,gate,gates,gauge,gave,gays,gaze,gear,gears,geek,geeks,geld,gems,gene,genes,genie,genre
genus,geoff,germ,get,gets,ghana,ghost,giant,gift,gifts,gigs,gild,giles,gill,gimp,gird,girl,girls,give,given
gives,glad,gland,glass,glee,glen,glenn,glide,glob,globe,gloom,glop,glory,gloss,glove,glow,glue,glum,gnat,gnaw
gnome,goad,goal,goals,goat,goats,god,gods,goes,going,gold,golf,gone,gong,gonna,good,goods,goose,gore,gorge
got,goth,goto,gotta,govt,gown,gowns,grab,grabs,grace,grad,grade,grain,gram,grams,grand,grant,grape,graph,gras
grasp,grass,grave,gray,great,greed,greek,green,greet,greg,gregg,grew,grey,grid,grief,grill,grim,grin,grind,grip
grips,grit,groan,groom,gross,group,grove,grow,grown,grows,grub,guam,guard,guess,guest,guide,guild,guile,guilt,guise
gulf,gull,gulp,gum,gun,guns,guru,gust,gusto,gut,guts,guys,gwen,gyms,gypsy,habit,hack,hacks,had,hague
haha,hail,hair,hairy,haiti,hale,half,hall,halls,halo,halt,ham,hand,hands,handy,hang,hangs,hank,hanna,hanoi
hans,happy,hard,hardy,hare,hark,harm,harp,harry,harsh,hart,hash,hast,haste,hat,hatch,hate,hated,hates,hath
hats,haul,haute,have,haven,havoc,hawk,hawks,hay,hayes,hays,haze,hazel,head,heads,heal,heap,hear,heard,hears
heart,heat,heath,heavy,heck,hedge,heed,heel,heels,hehe,heidi,heinz,held,helen,helix,hell,hello,helm,help,helps
hemp,hen,hence,henry,her,herb,herbs,herd,here,hero,hers,hertz,hicks,hide,hides,high,highs,hike,hill,hills
hilt,him,hindi,hindu,hinge,hint,hints,hip,hips,hire,hired,hires,his,hist,hit,hitch,hits,hive,hob,hobby
hog,hogan,hold,holds,hole,holes,holly,holt,holy,home,homer,homes,homme,homo,honda,honey,hong,honor,hood,hoods
hook,hooks,hoop,hoops,hop,hope,hoped,hopes,horde,horn,horns,horny,horse,hose,host,hosts,hot,hotel,hound,hour
hours,house,how,howe,howl,hub,hubs,hug,huge,hugh,hugo,hugs,hulk,hull,hum,human,humid,humor,hung,hunk
hunks,huns,hunt,huron,hurry,hurt,hurts,hush,husk,husky,hyde,hydro,hymn,hype,hyper,ibid,ibis,ice,icon,icons
idaho,idea,ideal,ideas,idiot,idle,idol,ieee,ill,image,imply,inch,incl,incur,index,india,indy,infer,info,infos
init,ink,inks,inlet,inn,inner,inns,input,inst,intel,inter,intl,into,intra,intro,ion,ionic,ions,iowa,iran
iraq,iraqi,irene,iris,irish,irk,iron,irons,irony,irwin,isaac,isdn,isis,islam,isle,isles,isnt,issue,italy,itch
item,items,ivan,ivory,ivy,jab,jack,jacks,jacob,jade,jail,jake,jam,james,jamie,jams,jane,janet,japan,jar
jared,jars,jason,java,jaw,jaws,jays,jazz,jean,jeans,jeep,jeer,jeff,jelly,jenna,jenny,jerk,jerry,jess,jesse
jest,jesus,jet,jets,jeux,jewel,jews,jihad,jill,jimmy,jive,joan,job,jobs,joel,joey,jog,johan,john,johns
join,joins,joint,joke,joker,jokes,jolly,jonah,jonas,jones,jong,jorge,jose,josh,jour,joy,joyce,juan,jude,judge
judy,jug,juice,juicy,jules,julia,julie,julio,july,jumbo,jump,jumps,june,junk,jury,just,kane,kappa,karen,karl
karma,kart,kate,kathy,katie,katy,kayak,kbps,keen,keep,keeps,keg,keith,kelly,kenny,keno,kent,kenya,kept,kern
kerry,kevin,key,keys,khan,kick,kicks,kids,kiev,kill,kills,kin,kind,kinds,king,kings,kinky,kiosk,kirby,kirk
kiss,kit,kite,kits,kitty,kiwi,klaus,knack,knee,kneel,knees,knew,knife,knit,knob,knobs,knock,knot,knots,know
known,knows,knox,koch,kodak,kona,kong,korea,kraft,kris,kung,kurt,kyle,kylie,kyoto,lab,label,labor,labs,lace
lack,lacks,laden,lady,lag,laid,lake,lakes,lama,lamb,lame,lamp,lamps,lance,land,lands,lane,lanes,lang,laos
lap,laps,lard,large,largo,lark,larry,lars,laser,lash,last,lasts,latch,late,later,latex,latin,laud,laugh,laura
lava,law,lawn,laws,lay,layer,lays,layup,lazy,lead,leads,leaf,leah,leak,leaks,lean,leap,learn,lease,least
leave,leds,leeds,left,leg,legal,legs,leigh,lemma,lemon,lena,lend,lenny,lens,lent,leon,leone,less,lest,let
lets,lett,level,lever,levi,levin,levy,lewis,liar,libby,libs,libya,lick,lid,lied,lien,liens,lies,lieu,life
lift,lifts,light,like,liked,likes,lilac,lilly,lily,lima,limb,limbs,lime,limit,limo,limp,linda,line,lined,linen
liner,lines,ling,link,links,linn,linus,lion,lions,lip,lipid,lips,lira,lisa,lisp,list,lists,lit,lite,liter
litre,live,lived,liver,lives,lloyd,load,loads,loan,loans,lobby,local,loch,lock,locks,locus,lodge,loft,log,logan
logic,login,logo,logos,logs,lohan,lois,lola,lone,long,look,looks,loom,loop,loops,loose,loot,lord,lords,lore
loren,lori,lorn,lose,loser,loses,loss,lost,lot,lots,lotto,lotus,loud,louis,love,loved,lover,loves,low,lowe
lower,lows,loyal,lucia,luck,lucky,lucy,luis,luke,lull,lulu,lump,luna,lunar,lunch,lung,lungs,lure,lush,lust
lute,lydia,lying,lymph,lynch,lynn,lynne,lynx,lyon,lyric,mace,mach,mack,macon,macro,macs,mad,madam,made,mafia
mage,magic,magna,mags,maid,mail,mails,main,maine,mains,maize,major,make,maker,makes,malay,male,males,mali,mall
malls,malta,mama,mambo,man,mana,mane,manga,mango,mania,mann,manor,mans,many,maori,map,maple,maps,mara,marc
march,marco,mardi,mare,maria,marie,mario,mark,marks,marry,mars,marsh,mart,marty,marx,mary,mash,mask,masks,mason
mass,mast,mat,match,mate,mates,math,maths,mats,matt,matte,maul,maven,maxi,maxim,maya,maybe,mayer,mayo,mayor
mazda,maze,mbps,mccoy,mead,meal,meals,mean,means,meant,meat,meats,medal,media,meet,meets,melt,memo,mens,ment
menu,menus,mercy,mere,merge,merit,merry,mesa,mesh,mess,messy,meta,metal,meter,meth,metre,metro,mets,miami,micah
mice,mick,micro,midi,midst,might,mike,mikes,milan,mild,mile,miles,milk,mill,mills,mime,mimi,mind,minds,mine
miner,mines,ming,mini,minor,mins,mint,minus,mips,mira,mire,misc,miss,missy,mist,misty,mitch,mixed,mixer,mixes
moan,moat,mob,mobil,mock,mod,modal,mode,model,modem,modes,mods,moist,mojo,mold,mole,molly,momma,mommy,moms
mona,monde,mondo,money,monk,monks,mono,mont,monte,month,monty,mood,moody,moon,moor,moore,moose,mop,moral,moran
more,morse,moses,moss,most,motel,moth,motif,motor,motto,mound,mount,mouse,mouth,move,moved,mover,moves,movie,much
muck,mud,muddy,mug,mugs,mule,multi,mummy,muse,music,must,mute,mutt,myth,myths,nach,nag,nail,nails,naive
naked,name,named,names,nancy,nanny,naomi,nap,napa,nasa,nasal,nash,nasty,natal,nate,natl,nato,naval,navy,nazi
nazis,neal,near,neat,neck,need,needs,needy,negro,neil,nelly,nemo,neon,nepal,nerd,nerve,ness,nest,nets,never
newer,newly,news,next,nexus,nice,niche,nicht,nick,nifty,nigel,night,nike,nikon,nile,nimb,nina,nine,ninja,ninth
nist,nitro,niue,nixon,noah,nobel,noble,nod,node,nodes,noel,noir,noise,noisy,none,noon,nope,nor,nora,norm
norma,norms,north,nose,not,notch,note,noted,notes,notre,noun,nous,nova,novel,novo,now,nude,nudes,nuke,null
nun,nurse,nut,nuts,nylon,nymph,oak,oaks,oar,oasis,oath,obese,obey,occur,ocean,octet,odd,odds,odes,odor
offer,offs,often,ogre,ohio,oil,oils,okay,old,older,olds,olive,olson,omaha,oman,omar,omega,omit,omni,once
one,ones,onion,only,onset,onto,onyx,oops,opal,open,opens,opera,opted,optic,opus,oral,orbit,order,ore,ores
organ,orgy,orig,orion,ortho,osaka,oscar,oslo,other,otis,otter,otto,ought,ounce,ours,outer,outs,oval,oven,ovens
over,owe,owed,owen,owing,owls,own,owned,owner,owns,oxide,ozone,pablo,pace,paced,pack,packs,pact,pad,paddy
pads,pagan,page,pager,pages,paid,pain,pains,paint,pair,pairs,pal,palau,pale,palm,palma,palms,pals,pan,panda
pane,panel,pang,panic,pans,pant,pants,panty,paolo,pap,papa,paper,papua,par,para,param,paris,park,parks,parse
part,parts,party,paso,pass,past,pasta,paste,pat,patch,path,paths,patio,patty,paul,paula,pause,pave,paved,paw
pay,pays,pea,peace,peach,peak,peaks,pear,pearl,peas,peat,peck,pedal,pedro,peek,peel,peer,peers,peg,peggy
pen,penis,penny,pens,pent,pepsi,per,percy,perry,pers,peru,peso,pesos,pest,pests,pet,pete,peter,petit,pets
petty,phase,phat,phil,phone,photo,phys,piano,pick,picks,pics,pie,piece,pier,pies,pig,pigs,pike,pile,piles
pill,pills,pilot,pimp,pin,pinch,pine,pines,ping,pink,pins,pint,pipe,piper,pipes,piss,pit,pitch,pits,pity
pivot,pixel,pizza,place,plaid,plain,plan,plane,plans,plant,plat,plate,plato,play,playa,plays,plaza,plea,plead,plod
plot,plots,plow,ploy,pluck,plug,plugs,plum,plump,plus,plush,pluto,pod,poem,poems,poet,poets,pogo,point,poker
polar,pole,poles,polk,poll,polls,polly,polo,poly,pond,ponds,pong,pony,pooh,pool,pools,poor,pop,pope,poppy
pops,porch,pore,pork,porn,porno,port,porto,ports,pose,posed,poses,post,posts,pot,pots,pouch,pound,pour,pow
power,pratt,pray,prep,pres,press,prev,prey,price,pride,prima,prime,print,prior,prism,prix,prize,prob,probe,proc
prod,prof,prog,prom,promo,prone,proof,prop,props,pros,prose,proto,proud,prov,prove,prow,proxy,prune,psalm,pub
publ,pubs,puff,puffy,pull,pulls,pulp,pulse,puma,pump,pumps,pun,punch,punk,punt,punta,pup,pupil,puppy,pure
purse,push,pussy,put,puts,qatar,quad,quake,quan,quark,quart,quasi,quay,queen,queer,query,quest,queue,quick,quiet
quilt,quit,quite,quiz,quot,quota,quote,rabbi,race,racer,races,rack,racks,radar,radio,rage,raid,rail,rails,rain
rains,rainy,raise,rake,rally,ralph,ram,rama,ramon,ramp,ramps,rams,ran,ranch,rand,randy,rang,range,rank,ranks
rant,rants,rap,rape,raped,rapid,rare,rash,rasp,rat,rate,rated,rates,ratio,rats,rave,raven,raw,ray,rays
razor,reach,react,read,reads,ready,real,realm,reap,rear,rebel,recap,recon,red,reds,reed,reef,reel,reels,reese
ref,refer,regal,reich,reid,reign,relax,relay,rely,remix,renal,renew,reno,rent,rents,rep,repay,repel,reply,reps
reset,resin,resp,rest,rests,retro,reuse,rhino,ribs,rice,rich,rick,ricky,rid,ride,rider,rides,ridge,rifle,rig
right,rigid,rile,riley,rim,rime,rims,ring,rings,rinse,riot,rip,ripe,rise,risen,rises,risk,risks,risky,rita
rite,ritz,rival,river,roach,road,roads,roam,roar,roast,rob,robe,robin,robot,roche,rock,rocks,rocky,rod,rode
rodeo,rods,roger,rogue,role,roles,roll,rolls,roman,rome,romeo,roms,roof,room,rooms,root,roots,rope,ropes,rosa
rose,roses,ross,rosy,rote,rotor,rouge,rough,round,rout,route,rove,rover,row,rowan,rows,roxy,royal,rsvp,rub
rubin,ruby,rude,rudy,rug,rugby,rugs,ruin,ruins,rule,ruled,ruler,rules,rum,rumor,run,runs,rupee,rural,rush
russ,rust,rusty,rut,ruth,ryder,sac,sack,sacks,sad,sadly,safe,safer,saga,sage,said,sail,saint,sakai,sake
salad,sale,salem,sales,sally,salon,salsa,salt,salts,samba,same,sammy,samoa,sand,sands,sandy,sane,sang,sank,sans
santa,santo,sap,sara,sarah,sash,sassy,sat,sata,satan,satin,sauce,saudi,saul,sauna,save,saved,saver,saves,savvy
saws,saxon,say,says,scale,scam,scams,scan,scans,scar,scare,scarf,scars,scary,scat,scene,scent,scion,scoop,scope
score,scots,scott,scout,scrap,screw,scrub,scuba,seal,seals,seam,sean,sear,sears,seas,seat,seats,secs,sect,sedan
seed,seeds,seek,seeks,seem,seems,seen,sees,seize,self,sell,sells,semi,send,sends,sense,sent,seoul,sept,serif
serum,serv,serve,set,seth,sets,setup,seven,sewer,sexes,sexy,shack,shade,shady,shaft,shah,shake,shall,shalt,shame
shane,shape,share,shark,sharp,shave,shaw,shawn,shea,shear,shed,sheds,sheep,sheer,sheet,shelf,shell,shift,shin,shine
shiny,ship,ships,shire,shirt,shit,shock,shoe,shoes,shook,shoot,shop,shops,shore,short,shot,shots,shout,show,shown
shows,shun,shut,siam,sich,sick,side,sided,sides,siege,siena,sigh,sight,sigma,sign,signs,silk,silky,sill,silly
silva,simon,sims,since,sind,sing,singh,sings,sink,sinks,sins,sinus,sion,sioux,sip,sir,sire,sit,site,sites
sith,sits,situ,sixth,sixty,size,sized,sizes,skate,skid,skies,skill,skin,skins,skip,skirt,skis,skull,skye,slab
slack,slam,slang,slap,slash,slat,slate,slave,sleek,sleep,slept,slice,slick,slide,slim,sling,slip,slips,sloan,slog
slop,slope,slot,slots,slow,slug,slum,slut,sluts,small,smart,smash,smell,smile,smith,smoke,smoky,snack,snake,snap
sneak,snip,snoop,snow,snowy,soak,soap,soaps,soar,sob,sober,sock,socks,sod,soda,sofa,sofas,sofia,soft,soho
soil,soils,solar,sold,sole,solid,solo,solve,soma,some,son,song,songs,sonic,sonny,sons,soon,soot,sop,sore
sorry,sort,sorts,sot,soul,souls,sound,soup,soups,sour,south,sow,soy,spa,space,spain,spam,span,spank,spans
spar,spare,spark,spas,spawn,speak,spear,spec,specs,speed,spell,spend,spent,sperm,spice,spicy,spies,spike,spill,spin
spine,spit,spite,split,spoke,spoon,sport,spot,spots,spray,spun,spur,spurs,spy,sqrt,squad,squid,stab,stack,stacy
staff,stag,stage,stain,stair,stake,stale,stalk,stall,stamp,stan,stand,star,stare,stark,starr,stars,start,stat,state
stats,stay,stays,steak,steal,steam,steel,steep,steer,stein,stem,stems,step,steps,stern,steve,stew,stick,stiff,still
sting,stir,stock,stoke,stole,stone,stony,stood,stool,stop,stops,store,storm,story,stout,stove,strap,straw,stray,strip
stub,stuck,stud,studs,study,stuff,stun,stunt,style,sub,subs,such,suck,sucks,sudan,sued,suede,sugar,suit,suite
suits,sulk,sum,sums,sun,sung,sunk,sunny,suns,sup,super,supp,suppl,supra,sure,surf,surge,susan,sushi,susie
swamp,swan,swap,swat,swear,sweat,sweep,sweet,swell,swept,swift,swim,swing,swiss,sword,sworn,swum,sync,syria,syrup
tab,table,taboo,tabs,tack,taco,tags,tail,tails,take,taken,takes,tale,tales,talk,talks,tall,tally,tame,tamil
tammy,tampa,tan,tang,tango,tank,tanks,tanya,tape,tapes,taps,tar,tara,tare,tarot,tart,task,tasks,taste,tasty
tate,taut,tax,taxes,taxi,taxis,teach,teak,teal,team,teams,tear,tears,teas,tease,tech,teddy,teem,teen,teens
tees,teeth,tele,tell,tells,temp,tempe,tempo,temps,ten,tend,tends,tenor,tens,tense,tent,tenth,tents,term,terms
terra,terre,terri,terry,test,tests,texas,text,texts,thai,than,thank,that,thats,the,thee,theft,their,them,theme
then,theo,there,these,theta,they,thick,thief,thigh,thin,thing,think,third,this,thong,thor,thorn,those,thou,three
threw,throw,thru,thug,thumb,thus,tibet,tick,tidal,tide,tides,tidy,tied,tier,ties,tiff,tiger,tight,tiki,tile
tiles,till,tilt,time,timed,timer,times,timor,tin,tina,tiny,tip,tips,tire,tired,tires,titan,title,tits,titus
toad,toast,toby,today,todd,toe,toes,togo,token,tokyo,told,toll,tomb,tome,tommy,ton,tone,toner,tones,tong
tonga,tons,tony,too,took,tool,tools,toon,toons,tooth,top,topaz,topic,tops,torah,torch,tori,torn,torso,tort
tory,toss,total,tote,touch,tough,tour,tours,tout,towel,tower,town,towns,toxic,toy,toys,trac,trace,track,tract
tracy,trade,trail,train,trait,tramp,tran,trans,trap,traps,trash,tray,trays,tread,treat,tree,trees,trek,trend,trent
tres,trial,tribe,trick,tried,tries,trim,trina,trio,trip,trips,trod,troll,troop,trout,troy,truck,true,truly,trump
trunk,trust,truth,try,tub,tube,tubes,tubs,tuck,tuft,tug,tulip,tulsa,tummy,tumor,tuna,tune,tuned,tuner,tunes
turbo,turf,turks,turn,turns,tutor,twain,tweak,tweed,twice,twig,twin,twink,twins,twist,two,tying,tyler,tyne,type
typed,types,typo,tyre,tyres,ugly,ulcer,ultra,uncle,uncut,under,undo,unify,union,unit,unite,units,unity,univ,unix
until,unto,upon,upper,upset,urban,urge,urged,urges,urine,urn,usage,use,used,user,users,uses,usher,using,ussr
usual,utah,util,utter,vague,vail,vain,vale,valet,valid,value,valve,van,vance,vane,vans,vapor,vary,vase,vases
vast,vat,vault,veal,vega,vegan,vegas,veil,vein,veins,venom,vent,venue,venus,vera,verb,verbs,verde,versa,verse
very,vest,vests,veto,vets,vibe,vice,vicki,video,view,views,vigor,viii,vile,villa,ville,vince,vinci,vine,vines
vinyl,viola,viper,viral,virus,visa,visas,vise,visit,visor,vista,vita,vitae,vital,vitro,viva,vivid,vivo,vocal,vodka
vogue,voice,void,vols,volt,volts,vote,voted,voter,votes,vow,vows,wacky,waco,wade,wag,wage,wages,wagon,waist
wait,waits,waive,wake,wales,walk,walks,wall,walls,walsh,walt,waltz,wand,wane,wang,wanna,want,wants,war,ward
wards,ware,warm,warn,warns,warp,wars,wary,was,wash,waste,watch,water,watt,watts,wave,waves,wax,wayne,ways
weak,weal,wean,wear,wears,weary,weave,web,weber,webs,wed,wedge,weed,weeds,week,weeks,weep,weigh,weir,weird
welch,weld,well,wells,welsh,welt,wend,wendy,went,were,west,wet,whale,wharf,what,whats,wheat,wheel,when,where
which,while,whip,whir,white,who,whole,whom,whore,whose,wide,wider,widow,width,wife,wig,wigan,wight,wigs,wild
wile,will,wills,willy,wilt,win,wind,winds,windy,wine,wines,wing,wings,wink,wins,wipe,wire,wired,wires,wise
wish,wisp,wit,witch,with,witty,wives,woe,woes,wok,woke,wolf,woman,women,won,wong,wont,woo,wood,woods
woody,wool,word,words,wore,work,works,world,worm,worms,worn,worry,worse,worst,wort,worth,would,wound,woven,wrap
wraps,wrath,wreck,wrist,writ,write,wrong,wrote,xerox,xiii,xmas,yacht,yahoo,yak,yale,yam,yang,yap,yard,yards
yarn,yeah,year,yearn,years,yeast,yell,yemen,yew,yield,ymca,yoga,yore,york,you,young,your,yours,youth,yowl
yuan,yukon,yummy,zach,zag,zaire,zap,zeal,zebra,zero,zesty,zeta,ziff,zinc,zion,zip,zone,zones,zoo,zoom
]]

for word in raw:gmatch("%a+") do
    if #word >= 3 and #word <= 5 then W[word] = true end
end

return W
