-- French word set for Wordladder (3-5 letters): curated common 3-letter words +
-- anagram.koplugin's frequency-filtered 4-5 letter words (OpenSubtitles top-N ∩ Scrabble-valid FR dict).
local W = {}
local raw = [[
abat,abats,abbe,abces,abime,aboie,abord,about,abri,abris,abus,abuse,acces,achat,acide,acier,acne,acres,acte,actes
actif,adieu,admet,admis,adore,ados,aerer,affut,afin,afro,agace,age,agee,agees,agent,ages,agile,agir,agira,agis
agit,agite,aida,aide,aidee,aider,aides,aidez,aient,aies,aigle,aigri,aigu,aigue,ail,aile,ailes,aille,aime,aimee
aimer,aimes,aimez,aine,ainee,aines,ainsi,aire,aires,airs,aise,album,alias,alibi,alla,alle,allee,aller,alles,allez
allie,allo,alors,alpes,alpha,alvin,amant,amas,ambre,amen,amene,amer,amere,ames,ami,amie,amies,amis,amont,amour
amuse,anal,ancre,ane,anes,ange,anges,angle,anime,annee,antan,antre,anus,aorte,aout,appat,appel,appui,apres,apte
arabe,arbre,arc,arche,arene,ares,argot,argus,aria,arme,armee,armer,armes,armez,arret,art,arts,asile,assez,assis
athee,atlas,atome,atout,aube,aucun,audio,audit,aura,aurai,auras,aurez,aussi,autel,auto,autos,autre,avais,avait,aval
avale,avant,avare,avec,avere,aveu,aveux,avez,avide,aviez,avion,avis,avise,avoir,avons,avoue,avril,axe,ayant,ayez
ayons,azote,azur,baba,baby,bac,bache,bacle,bacon,badge,baffe,bague,bahut,baie,baies,bail,bain,bains,baise,bal
balai,balle,bals,banal,banc,bancs,bande,bang,banjo,banni,bar,barbe,barbu,barge,baril,baron,barre,bars,bas,base
basee,bases,basse,bates,bati,batie,batir,baton,bats,batte,battu,baume,bave,baver,bayou,bazar,beat,beau,beaux,bebe
bebes,bec,beige,belge,belle,beni,benie,benir,benis,benne,beret,beta,bete,betes,beton,bette,biais,bibi,bible,biche
bide,bidon,bien,biens,biere,bijou,bilan,bile,bill,bille,bingo,bio,bise,bison,bisou,bite,bites,bizut,black,blair
blame,blanc,ble,bled,bleu,bleue,bleus,bloc,blocs,blond,blues,bluff,bobo,bocal,boche,boeuf,boira,boire,bois,boit
boite,boive,bol,bols,bombe,bon,bond,bonde,bonne,bons,bonte,bonus,boom,bora,bord,bords,borne,bosco,boss,bosse
bossu,botte,bouc,boude,boue,bouee,bouge,boule,boum,boume,bouse,bout,bouts,boxe,boxer,boys,bras,brave,bravo,break
bref,breve,brick,bride,brin,bris,brise,bruit,brule,brume,brun,brune,bruns,brut,brute,buche,bug,bulle,bus,bush
buste,but,bute,buter,butin,buts,butte,buvez,cable,cabot,caca,cacao,cache,cade,cadet,cadre,cafe,cafes,cage,cages
caid,cake,cale,calin,calme,came,cames,camp,camps,canal,cane,canne,canoe,canon,canot,cap,cape,capot,capte,car
cargo,carpe,carre,carte,cas,casa,case,caser,cases,cash,casse,catch,catin,cause,cave,caves,ceci,cede,ceder,cela
celle,celui,cense,cent,cents,cerf,cerfs,cerne,ces,cesar,cesse,cette,ceux,chair,chale,champ,chant,chaos,char,chars
chat,chats,chaud,chef,chefs,chene,cher,chere,cheri,chers,chez,chic,chics,chie,chien,chier,china,chine,chiot,chips
choc,chocs,choix,chope,chose,chou,choux,chut,chute,ciao,cible,cidre,ciel,cieux,cils,cine,cinq,cire,cirer,cite
citer,cites,civil,clair,clamp,clan,clans,cle,clebs,clef,clefs,cles,clic,clics,clin,clip,clive,clodo,clone,clope
clore,clos,close,clou,cloue,clous,clown,club,clubs,coach,cobra,coca,coche,coco,cocon,cocos,cocu,code,codes,coeur
cogne,coin,coins,coke,col,cola,colin,colis,colle,colon,cols,colt,coma,comme,comte,concu,cone,conge,connu,cons
conte,cool,copie,coq,coqs,coque,cor,coran,corde,corne,corps,corse,cote,cotes,coton,cou,coude,coule,coup,coupe
coups,cour,cours,court,couru,cousu,cout,coute,couts,crabe,crac,crack,craie,crame,cran,crane,crash,crea,cree,creee
creer,crees,creez,creme,crepe,crete,creux,creve,cri,cric,crie,crier,cries,criez,crime,cris,crise,crocs,croie,crois
croit,croix,cross,cru,crue,cruel,crus,cuba,cube,cubes,cuir,cuire,cuit,cuite,cuits,culot,culs,culte,cure,curry
cuve,cycle,cygne,dada,dague,daim,dalle,damas,dame,dames,damne,dandy,dans,danse,dard,data,date,dates,daube,debat
debit,debut,deca,deces,dechu,decor,decu,decue,decus,dedie,defi,defie,defis,degat,degre,deja,dela,delai,delia,delit
delta,demi,demie,demon,deni,denis,dense,dent,dents,depit,depot,derby,desir,dette,deuil,deux,devez,devie,devin,devis
devra,diane,dicte,dieu,dieux,digne,digue,dina,dinde,dine,diner,dinez,ding,dingo,dira,dirai,diras,dire,direz,disco
dise,dises,dite,dites,dits,diva,divan,divin,dock,docks,dodo,doigt,dois,doit,doive,dome,donc,donna,donne,dons
dont,dope,dora,dore,doree,dores,doris,dorme,dormi,dors,dort,dos,dose,doses,dote,douce,doue,douee,doues,doute
doux,douze,doyen,drain,drame,drap,draps,drill,dring,drive,droit,drole,drop,duc,duel,dues,dune,dunes,duo,dupe
duper,dur,dure,duree,durer,dures,durs,duvet,eau,eaux,ecart,echec,echo,eclat,ecole,ecran,ecris,ecrit,ecume,eden
effet,egal,egale,egard,egare,egaux,ego,egout,elan,eleve,elfe,elfes,elire,elise,elite,elle,elles,eloge,elu,elue
elus,email,emet,emis,empli,emue,encre,enfer,enfin,enfle,enfui,engin,enjeu,ennui,entra,entre,envie,envoi,envol,epais
epate,epave,epee,epees,epi,epice,epine,epoux,epris,erre,errer,essai,essor,etage,etais,etait,etang,etant,etape,etat
etats,etau,ete,etend,etes,ether,etiez,etire,etre,etres,etude,etui,eues,euros,eux,evade,eveil,evier,evite,exact
exces,exclu,exige,exil,exile,extra,face,faces,fache,facon,fade,faim,faire,fais,fait,faite,faits,fallu,fane,farce
fasse,fatal,faune,faut,faute,fauve,faux,fax,fee,fees,feint,fele,femme,femur,fend,fendu,fente,fer,fera,ferai
feras,ferez,ferie,ferme,ferry,fers,fesse,fete,feter,fetes,feu,feux,fibre,fiche,fichu,fief,fier,fiere,fiers,fige
fil,file,filer,files,filet,filez,fille,film,filme,films,filon,filou,fils,fin,final,fine,fines,fini,finie,finir
finis,finit,fins,fiole,firme,fisc,fit,fixe,fixee,fixer,fixes,fixez,flair,flan,flanc,flash,fleau,fleur,flic,flics
flint,flirt,flot,flots,flou,floue,flush,flute,flux,foie,foin,foire,fois,fol,folie,folk,folle,fonce,fond,fonde
fonds,fondu,font,fonte,foot,force,forer,foret,forge,forme,fort,forte,forts,forum,fosse,fou,fouet,foule,four,fours
fous,fout,foute,foutu,foyer,frais,franc,frein,frere,fric,frigo,frime,frire,frise,frit,frite,fritz,froc,froid,frole
front,fruit,fuel,fugue,fuir,fuis,fuit,fuite,full,fume,fumee,fumer,fumes,fumez,funky,furax,furet,furie,fusee,fusil
fute,futee,futes,futur,fuyez,gable,gache,gaffe,gag,gaga,gage,gages,gagne,gaie,gain,gaine,gains,gais,gala,gale
gallo,galop,gamin,gamme,gang,gangs,gant,gants,garce,garde,gare,garee,garer,gares,gars,gate,gatee,gater,gates,gaule
gave,gay,gays,gaz,gaza,gaze,gazon,geant,gel,gele,gelee,geler,geles,gemir,gemit,gemma,gene,genee,gener,genes
genez,genie,genou,genre,gens,gerbe,gere,gerer,geres,gerez,geste,gifle,gilet,girl,girls,gitan,gite,givre,glace,gland
glass,globe,glu,gnole,gobe,gober,gogo,golf,golfe,gomme,gong,gorge,gosse,gout,goute,gouts,grace,grade,grain,grand
gras,grave,gre,great,grec,grecs,green,greer,grele,greve,grill,gris,grise,groom,gros,group,grue,guepe,guere,gueri
guet,guide,guise,habit,hache,hadji,haie,haine,hair,hais,hait,hale,hall,halo,halte,hamac,hante,harem,harpe,hart
hate,haut,haute,hauts,have,havre,hein,helas,hello,henry,herbe,here,heros,heure,hibou,hier,hindi,hisse,hiver,hobby
hola,home,homme,homo,homos,honte,horde,hors,hosto,hote,hotel,hotes,huile,huit,hurle,hutte,hymne,icone,ideal,idee
idees,idem,idiot,idole,ile,iles,image,imam,imite,imper,impie,impot,inde,index,inne,inoui,insu,ion,irai,irais
irait,iras,irez,iriez,iris,irons,iront,islam,isole,issu,issue,issus,ivre,ivres,jack,jade,jadis,jambe,japon,jaser
jaune,java,javel,jazz,jean,jeans,jeep,jenny,jesus,jete,jetee,jeter,jetes,jetez,jeton,jets,jette,jeu,jeudi,jeun
jeune,jeux,job,jobs,joie,joies,joins,joint,joker,joli,jolie,jolis,joue,jouee,jouer,joues,jouet,jouez,joug,joui
jouir,jouis,jour,jours,joyau,judas,judo,juge,jugee,juger,juges,jugez,juif,juifs,juin,juive,jules,jupe,jupes,jure
jurer,jures,jurez,jury,jus,jusqu,juste,kali,kappa,karma,khan,kiki,kilo,kilos,kit,kyste,label,lac,lacet,lache
lacs,lady,laid,laide,laine,laird,lait,lama,lame,lames,lampe,lance,lande,lange,lapin,laps,lard,large,larme,larve
laser,lasse,lasso,latex,latin,latte,lave,lavee,laver,laves,lavez,leche,lecon,legal,leger,legs,legue,lent,lente,lents
leur,leurs,leve,levee,lever,leves,levez,levre,lexie,libre,lie,liee,liees,lien,liens,lier,lies,lieu,lieux,ligne
ligue,lilas,lima,lime,linge,lion,lions,lira,lirai,liras,lire,lise,lises,lisez,lisse,liste,lit,litre,lits,live
livre,lobe,local,loft,loge,logee,loger,loges,logis,logo,loi,loin,lois,long,longs,look,loque,lord,lords,lori
lors,lot,loto,lots,lotus,loue,louee,louer,louez,louis,loup,loupe,loups,lourd,love,loyal,loyer,lueur,luge,lui
luis,lulu,lundi,lune,lunes,lupus,lutin,lutte,luxe,lycee,lynx,mache,macho,macon,mafia,magie,magne,magot,maia,mail
mails,main,mains,maire,mais,major,maki,mal,male,males,malin,malle,malt,maman,mamie,mange,manie,marc,mardi,mare
maree,marge,mari,maria,marie,marin,maris,mark,marks,marre,mars,masse,mata,match,mate,mater,mates,matez,math,maths
matin,mauve,maux,maya,meche,mecs,media,mefie,mele,melee,meler,meles,melez,melon,meme,memes,mene,menee,mener,menes
menez,mens,ment,mente,menti,menu,menus,mer,merci,merde,mere,meres,merle,mers,mes,mesa,mess,messe,metal,meteo
metis,metre,metro,mets,mette,meure,meurs,meurt,meute,miaou,micro,midi,miel,mien,miens,mieux,mil,milan,mile,miles
mille,mime,mimi,mina,mince,mine,mines,minet,mini,minou,minus,mira,mire,mise,miser,mises,miss,mixer,mixte,moche
mode,modes,moine,moins,moira,mois,moise,moisi,moite,molle,mollo,mome,momes,momie,monde,mont,monte,monts,moque,moral
mord,mords,mordu,more,morse,mort,morte,morts,morue,morve,motel,motif,moto,motos,mots,motus,mou,moule,mous,moyen
muet,muets,mule,mules,mur,mure,mures,muri,murs,muse,musee,must,mute,muter,mythe,nabot,nage,nager,naif,nain
naine,nains,nait,naive,nana,nanas,nappe,nase,natal,naval,navet,navre,nazi,nazie,nazis,neant,nees,negre,neige,nenes
nerf,nerfs,net,nets,nette,neuf,neufs,neuve,neveu,nez,niais,niche,nid,nids,niece,nier,niez,nique,noble,noce
noces,noeud,noie,noir,noire,noirs,noix,nom,nomme,noms,nonne,nope,nord,norme,nos,note,noter,notes,notez,notre
noue,nouer,nous,nova,noyau,noye,noyee,noyer,noyes,nuage,nue,nues,nuire,nuit,nuits,nul,nulle,nuls,nuque,nurse
nylon,oasis,obei,obeir,obeis,obeit,obese,objet,obus,ocean,odeur,oeil,oeuf,oeufs,offre,ogive,ogre,oie,oies,olive
ombre,omega,omis,once,oncle,onde,ondes,ongle,ont,onze,open,opera,opere,opium,opte,orage,oral,orale,ordre,orge
orgie,orgue,osais,oscar,ose,osent,oser,osera,oses,osez,otage,ote,oter,otez,ouais,oubli,ouest,oui,ouie,ours
ourse,ouste,outil,outre,ouvre,ovale,ovni,ovnis,ovule,oxyde,ozone,pacha,pack,pacte,paddy,page,pages,paie,paien,paies
pain,pains,pair,paire,pairs,paix,pale,pales,palet,pan,panda,panne,paon,papa,papas,pape,papi,papy,par,para
parc,parce,parcs,pardi,pare,parer,pares,parez,pari,paria,parie,paris,parla,parle,parmi,paroi,pars,part,parte,parti
parts,paru,pas,passa,passe,pate,patee,pates,patio,patte,paume,pause,pave,paye,payee,payer,payes,payez,pays,peage
peau,peaux,peche,pegre,peine,peins,peint,pekin,pelle,penal,pend,pendu,penis,penny,pense,pente,pepe,pepin,perce,percu
perd,perde,perds,perdu,pere,peres,peri,peril,perir,perle,perse,perte,pese,peser,pesos,peste,pete,peter,petes,petit
peu,peur,peurs,peut,peux,pfft,phare,phase,philo,photo,piano,pic,pics,pie,piece,pied,pieds,piege,pieu,pieux
pige,piger,piges,pigez,pile,piles,pille,pin,pince,pinot,pins,pinte,pion,pions,pipe,piper,pipes,pipi,pique,pire
pires,pisse,piste,pitie,pizza,place,plage,plaie,plais,plait,plan,plane,plans,plat,plate,plats,plein,pleut,pli,plie
plier,plis,plomb,plouc,pluie,plume,plus,pneu,pneus,poche,poele,poeme,poete,poids,poil,poils,poilu,poing,point,poire
pois,poker,pole,poli,polie,polio,polis,polo,pomme,pompe,pond,pondu,poney,pont,ponte,ponts,pope,porc,porcs,pores
porno,port,porte,porto,ports,pose,posee,poser,poses,posez,poste,pot,pote,potes,pots,pou,pouce,pouf,poule,pouls
poupe,pour,poux,pre,prend,pres,pret,prete,prets,prevu,prie,prier,pries,priez,prime,primo,pris,prise,prit,prive
prix,prof,profs,proie,promo,promu,pros,proue,prude,prune,psy,puait,puant,pub,pubs,puce,puces,puent,pues,puis
puits,pull,pulls,puma,punch,puni,punie,punir,punis,punit,punk,punks,pur,pure,puree,pures,purge,purs,put,pute
putes,quai,quais,quand,quant,quark,quart,quasi,quel,quels,quete,queue,qui,quint,quoi,quota,race,races,racle,radar
rade,radin,radio,radis,rafle,rage,raid,raide,raids,raie,rail,rails,raina,raja,rale,raler,rame,ramer,rames,rampe
ranch,rang,range,rangs,rani,rap,rare,rares,ras,rase,rasee,raser,rat,rate,ratee,rater,rates,ratez,raton,rats
rave,ravi,ravie,ravin,ravir,ravis,raye,rayer,rayon,reagi,real,rebut,recel,recif,recit,recu,recue,recul,recus,redis
reel,reels,refus,regal,regle,reglo,regne,rein,reine,reins,rejet,relax,relie,relu,remet,remis,remue,rend,rende,rends
rendu,rene,renee,renes,renie,renne,rente,repas,repit,repli,repos,resta,reste,retro,reuni,reve,revee,rever,reves,revez
revu,revue,revus,rhum,rhume,riait,riant,riche,ride,rider,rides,rien,rient,riez,rime,rimes,ring,rira,rire,rires
risee,rite,rites,rival,rive,river,rives,riz,robe,robes,robin,robot,roche,rock,rode,rodeo,roder,rogne,roi,rois
role,roles,roman,romps,rompt,rompu,rond,ronde,ronds,ronge,rosa,rose,rosee,roses,rosie,roti,rotir,roue,roues,rouge
roule,round,route,roux,royal,ruban,rubis,ruche,rude,rue,ruee,rues,rugby,ruine,ruse,rusee,ruses,rush,russe,sable
sabot,sabre,sac,sache,sacre,sacs,saga,sage,sages,sain,saine,sains,saint,sais,saisi,sait,sake,sale,salee,sales
sali,salir,salis,salle,salon,salsa,salue,salut,salve,samba,sang,sans,sante,saoul,saper,sapin,satin,sauce,sauf,sauna
saura,saut,saute,sauts,sauve,savez,savon,saxon,sceau,scene,scie,scoop,score,scout,seau,seaux,sec,seche,secs,secte
sein,seine,seins,seize,sel,selle,selon,sels,seme,semer,semes,senat,sens,sense,sent,sente,senti,sept,sera,serai
seras,serbe,serez,serge,serie,serre,sers,sert,serum,serve,servi,ses,seuil,seul,seule,seuls,seve,sexe,sexes,sexy
shah,shoot,short,show,shows,sied,siege,sien,siens,sieur,signe,silo,singe,sinon,sinus,sioux,sire,sirop,site,sites
sitot,situe,six,skate,ski,skier,skis,slip,slips,slow,smash,snack,snob,sobre,soda,sodas,soeur,sofa,soi,soie
soif,soin,soins,soir,soirs,sois,soit,soja,sol,solde,solo,sols,somme,son,sonar,sonde,songe,sonne,sono,sons
sont,sors,sort,sorte,sorti,sorts,sosie,sot,sotte,souci,soude,soul,soule,soupe,sourd,souri,sous,soute,soyez,sport
spot,spots,spray,stade,staff,stage,stand,star,stars,stase,steak,stick,stock,stop,store,style,stylo,subi,subir,subis
subit,suce,sucer,sucre,sud,suede,suer,sueur,suis,suit,suite,suive,suivi,sujet,super,sur,sure,sures,surf,surgi
surs,sushi,swing,sympa,tabac,table,tabou,tache,tact,taire,tais,taise,tait,talc,talon,tango,tank,tanks,tant,tante
tape,taper,tapes,tapez,tapis,tara,tard,tarde,tare,taree,tares,tarif,tarte,tas,tasse,tata,tate,tater,taule,taupe
taux,taxe,taxes,taxi,taxis,teint,tele,teles,tell,telle,tels,tempe,tempo,temps,tend,tends,tendu,tenez,tenir,tente
tenu,tenue,tenus,terme,terne,terra,terre,terri,test,teste,tests,tete,tetes,teton,tetu,tetue,texan,texte,the,theme
these,thon,thune,tibia,tiede,tien,tiens,tient,tiers,tige,tigre,tire,tiree,tirer,tires,tirez,tirs,tissu,titan,titra
titre,toast,toi,toile,toit,toits,tole,tomas,tomba,tombe,tommy,ton,tonne,tons,top,tope,topo,toque,tord,tordu
torse,tort,torts,tory,tot,total,totem,toto,tour,tours,tous,tout,toute,toux,trac,trace,trahi,train,trait,tram
trame,tres,treve,tri,tribu,trier,trio,trip,troc,trois,troll,tronc,trone,trop,trot,trou,troue,trous,truc,trucs
truie,trust,tsar,tuais,tuait,tuant,tuba,tube,tubes,tue,tuee,tuees,tuent,tuer,tuera,tues,tueur,tuez,tuile,tuons
turc,turcs,tuyau,twist,type,types,tyran,ultra,unes,unie,unies,union,unir,unis,unit,unite,urine,urne,usage,use
usee,usees,user,usine,usure,utile,vache,vagin,vague,vain,vaine,vais,valet,valez,valse,valu,valve,vanne,vante,vapes
varie,vas,vase,vaste,vaut,vaux,veau,vecu,vecue,veine,velo,velos,vend,vende,vends,vendu,venez,venge,venin,venir
vent,vente,vents,venu,venue,venus,verbe,verra,verre,vers,versa,verse,vert,verte,verts,vertu,veste,veto,vetu,vetue
veuf,veut,veuve,veux,vexe,vexee,vexer,vibre,vice,vices,vide,videe,video,vider,vides,videz,vie,vieil,viens,vient
vies,vieux,vifs,vigne,vil,vile,villa,ville,vin,vingt,vins,vint,viol,viola,viole,viols,viral,vire,viree,virer
vires,virez,viril,virus,visa,visas,vise,visee,viser,vises,visez,vison,vit,vital,vite,vitre,vive,vives,vivez,vivra
vivre,vocal,vodka,voeu,voeux,vogue,voici,voie,voies,voila,voile,voir,voire,vois,voit,voix,vol,vole,volee,voler
voles,volet,volez,vols,volts,vomi,vomir,vomis,vomit,vont,vos,vote,voter,votes,votez,votre,voue,voulu,vous,voute
voyez,voyou,vrac,vrai,vraie,vrais,vues,wagon,watts,web,weber,yacht,yang,yard,yards,yens,yeux,yoga,yogi,zebre
zele,zero,zeros,zeta,zinc,zizi,zone,zones,zoo,zoom
]]

for word in raw:gmatch("%a+") do
    if #word >= 3 and #word <= 5 then W[word] = true end
end

return W
