-- Minimal English word list for Boggle (3–8 letters, common words)
local W = {}
local raw = [[
ace,act,add,age,ago,aid,aim,air,all,and,ant,any,apt,arc,are,ark,arm,art,ask,ate,awe,axe,aye,
bad,bag,ban,bar,bat,bay,bed,beg,bet,bid,big,bit,box,boy,bud,bug,bun,bus,but,buy,
cab,can,cap,car,cat,cob,cod,cog,cop,cot,cow,cry,cub,cup,cut,
dab,dad,dam,dip,dog,dot,dry,dub,dug,dun,
ear,eat,egg,ego,elf,elm,end,era,eve,ewe,eye,
fad,fan,fat,fee,few,fig,fin,fit,fix,fly,fog,foe,for,fox,fry,fun,fur,
gag,gap,gas,get,god,got,gum,gun,gut,
had,ham,hat,hay,hen,her,him,hip,his,hit,hob,hog,hop,hot,how,hub,hug,hum,
ice,ill,ink,inn,ion,irk,ivy,
jab,jam,jar,jaw,jet,job,jog,joy,jug,
keg,key,kin,kit,
lab,lag,lap,law,lay,leg,let,lid,lip,lit,log,lot,low,
mad,man,map,mat,mob,mod,mop,mud,mug,
nag,nap,nod,nor,not,now,nun,nut,
oak,oar,odd,oil,old,one,ore,owe,own,
pad,pal,pan,pap,par,pat,paw,pay,pea,peg,pen,per,pet,pie,pig,pin,pit,pod,pop,pot,pow,pub,pun,pup,put,
ram,ran,rap,rat,raw,ray,red,ref,rep,rid,rig,rim,rip,rob,rod,row,rub,rug,rum,run,rut,
sac,sad,sap,sat,say,set,sip,sir,sit,sob,sod,son,sop,sot,sow,soy,spa,spy,sub,sum,sun,sup,
tab,tan,tar,tax,ten,the,tin,tip,toe,ton,too,top,toy,try,tub,tug,two,
urn,use,
van,vat,vow,
wag,war,was,wax,web,wed,wet,who,wig,win,wit,woe,wok,won,woo,
yak,yam,yap,yew,you,
zag,zap,zip,zoo,
able,ache,acid,aged,also,alto,arch,area,arms,army,arts,aunt,
back,bail,bait,bake,bale,ball,balm,band,bane,bank,bare,barn,base,bash,bask,bath,bear,beat,beef,been,beer,beet,bell,belt,bend,best,bile,bill,bind,bird,bite,blab,blah,blam,blaze,blew,blob,blue,blur,bold,bolt,bone,bore,both,bowl,brag,bray,bred,brew,brim,brow,buck,buff,bulk,bull,bump,bunk,burn,burp,bury,bush,buzz,
cake,call,calm,came,camp,cane,care,cart,case,cash,cast,cave,cell,cent,chad,chap,char,chip,chop,chub,cite,city,clam,clap,claw,clay,clip,clod,clop,clog,club,clue,coal,coat,code,coil,coin,come,cone,cook,cool,cope,cord,core,corn,cost,cozy,cram,crew,crop,crow,cube,cuff,cure,curl,curt,cute,
damp,dare,dark,dart,data,date,dawn,days,dead,deaf,deal,dean,dear,debt,deck,deed,deep,deer,dent,deny,desk,dike,dill,dime,dine,dire,dirt,dish,disk,dive,dock,doff,dole,dome,doom,dorm,dose,dote,dove,down,drab,drag,draw,drew,drip,drop,drug,drum,duck,dude,duel,dull,dumb,dung,dusk,dust,duty,
each,earl,earn,ease,east,easy,edge,emit,even,ever,evil,exam,eyes,
face,fact,fail,fair,fake,fall,fame,fang,fare,farm,fast,fate,fawn,faze,fear,feat,feed,feel,feet,fell,felt,fend,fern,fest,fete,fill,film,find,fine,fire,fish,fist,five,flag,flap,flat,flaw,flea,flew,flip,flog,flop,flow,foam,fold,folk,fond,font,food,fool,ford,fore,fork,form,fort,four,fowl,from,fuel,full,fund,fuse,fuzz,
gale,gall,game,gang,gape,garb,gash,gate,gave,gaze,gear,geld,germ,gift,gild,gird,girl,give,glee,glen,glob,glop,glow,glue,glum,gnat,gnaw,goad,goat,gold,gone,gong,good,gore,gown,grab,gray,grew,grid,grim,grin,grip,grit,grow,grub,gulf,gull,gulp,gust,guts,guys,
hack,hale,half,hall,halt,hand,hang,hard,hare,hark,harm,harp,hash,hate,haul,have,hawk,haze,head,heal,heap,hear,heat,heel,heed,held,helm,help,herd,here,hero,hide,high,hill,hilt,hint,hire,hive,hold,hole,home,hood,hook,horn,hose,hour,howl,hull,hunt,hurt,husk,
idea,idle,iris,iron,isle,itch,
jade,jail,jeer,jest,jump,junk,just,
keen,keep,kill,kind,king,knit,know,
lace,lack,laid,lake,lamb,lamp,land,lane,lard,lark,lash,last,late,laud,lava,lazy,lead,leaf,lean,leap,left,lend,lens,lick,life,lift,like,lime,line,link,lion,list,live,load,loan,lock,loft,lone,long,look,loom,loot,lord,lore,lore,lorn,lose,loss,love,lull,lump,lung,lure,lust,lute,
mace,made,mail,main,make,male,mall,mane,many,mare,mark,mart,mash,mask,mass,mast,mate,maul,meal,mean,meat,melt,memo,mere,mesh,mice,mile,mill,mime,mine,mint,mire,miss,mist,moan,moat,mock,mold,mole,monk,moon,moor,more,moss,most,moth,move,much,muck,mutt,myth,
nail,name,need,nest,next,nice,nimb,nine,norm,note,noun,
obey,odes,ogre,once,ones,only,open,oral,ores,over,
pace,pack,page,paid,pain,pair,pale,palm,pang,papa,park,part,pass,past,path,pave,peak,pear,peat,peel,peer,pent,pick,pier,pike,pile,pill,pine,pink,pint,pipe,plan,plod,plot,plow,ploy,plum,plus,poem,poet,pole,poll,pore,pork,porn,port,pose,post,pour,pray,prod,prop,prow,pull,pump,pure,push,
quay,quiz,
race,rack,rain,rake,ramp,rang,rank,rant,rasp,rate,rave,read,real,reap,reef,reel,rent,rest,rice,rich,ride,rile,rime,ring,riot,rise,risk,roam,roar,robe,rock,role,roll,roof,room,root,rope,rose,rosy,rote,rout,rove,rude,ruin,rule,rush,rust,
safe,sage,sail,sake,sale,salt,same,sand,sane,sang,sank,sash,save,seal,seam,sear,seat,seed,seek,seen,self,sell,send,sent,shed,shin,ship,shoe,shop,shot,shun,shut,sick,side,sigh,silk,sill,sing,sink,site,size,skid,skip,slab,slap,slat,slim,slip,slog,slop,slow,slug,slum,snap,snip,snow,soak,soap,soar,sock,sole,some,song,soot,sort,soul,sour,span,spar,spin,spit,spot,spun,spur,stab,stag,star,stay,stem,step,stir,stun,such,suck,suit,sulk,sung,sunk,sure,swan,swap,swat,swim,swum,
tack,tail,tale,tall,tame,tank,tape,tare,tart,task,taut,team,tear,teem,tell,tent,test,text,than,that,them,then,they,thin,this,thou,thus,tick,tide,tile,till,time,toad,toll,tome,tone,tong,tool,torn,toss,town,track,trap,tray,tree,trim,trio,trip,trod,true,tuck,tuft,tuna,tune,turn,twig,type,
ugly,undo,unit,upon,
vale,vane,vase,vast,veal,veil,vein,very,vest,veto,vice,view,vile,vine,vise,void,volt,vote,
wade,wake,walk,wall,wand,wane,ward,warm,warn,wary,wash,wave,ways,weak,weal,wean,weed,week,weep,well,welt,wend,went,were,west,what,when,whip,whir,wide,wile,will,wilt,wind,wine,wing,wink,wire,wise,wish,wisp,with,wolf,wood,wool,word,wore,work,worm,worn,wort,
yard,yarn,year,yell,yoga,yore,your,yowl,
zeal,zero,zone,
abide,abode,abort,about,above,abuse,actor,acute,after,again,agent,agree,ahead,aisle,alarm,album,alert,allay,allot,allow,alone,aloud,alter,amend,amino,ample,angel,anger,ankle,annex,apart,apple,apply,arena,argue,arise,armor,army,array,arrow,aside,asset,atlas,attic,audio,audit,avoid,aware,awful,
baker,bases,basic,basis,beach,beard,beast,below,bench,bible,black,blade,blame,bland,blank,blast,blaze,bleed,blend,blind,block,blood,bloom,blown,board,bonus,boost,booth,bound,boxer,brain,brand,brave,bread,break,bride,brief,bring,broad,brook,brown,build,built,burst,buyer,
cabin,camel,candy,cargo,carry,catch,cause,chain,chair,chalk,charm,chart,chase,cheap,check,cheek,cheer,chess,chest,chick,chief,child,china,chips,civil,claim,class,clean,clear,climb,clock,clone,close,cloud,coach,coast,cobra,coded,comet,comic,comma,coral,count,court,cover,crack,craft,crane,crash,crazy,cream,crime,crisp,cross,crowd,crown,crush,crypt,curve,cycle,
dance,death,debut,delay,dense,depth,devil,diary,disco,dodge,doubt,dough,draft,drain,drama,dream,dress,drift,drink,drive,drone,drown,dryer,
eagle,early,earth,eight,elite,email,ember,empty,enemy,enjoy,enter,entry,equal,essay,evade,event,exact,exalt,exile,exist,extra,
fable,faith,fancy,fault,feast,fence,feral,fever,fiber,field,fifth,fifty,fight,final,first,fixed,flame,flash,flask,fleet,flesh,flick,flock,flood,floor,flour,flown,fluid,flush,focus,force,forge,forth,found,frame,frank,fraud,fresh,front,frost,fruit,fully,funky,funny,
gains,gauge,ghost,giant,given,gland,glass,globe,gloom,glory,gloss,glove,grace,grade,grain,grand,grant,grape,grasp,grass,grave,great,greed,green,greet,grief,grill,grind,groan,grove,grown,guard,guess,guild,guile,guise,gusto,
habit,hands,happy,harsh,haste,hatch,heart,hedge,hence,hertz,hinge,hobby,holly,honor,horse,hotel,house,human,humid,humor,hurry,
image,imply,infer,inner,input,inter,intro,issue,ivory,
jewel,joint,joker,jolly,judge,juice,juicy,jumbo,
karma,knack,kneel,knife,knock,known,
label,large,laser,latch,later,learn,lease,least,leave,level,light,limit,liner,liver,local,lodge,logic,loose,lower,lucky,lunar,lunch,
magic,maker,manor,maple,march,match,mayor,media,mercy,merge,merit,metal,might,minor,minus,mixer,model,money,month,moral,mound,mount,mouse,movie,music,
naval,nerve,never,night,noble,north,notch,noted,novel,nurse,nymph,
ocean,offer,often,olive,onion,onset,opera,orbit,order,outer,owned,owner,oxide,ozone,
paint,panel,panic,paper,patch,pause,peace,peach,pearl,pedal,penny,phase,piano,pilot,pinch,pixel,pizza,place,plain,plane,plant,plate,plaza,plead,pluck,point,polar,porch,power,press,price,pride,prime,print,prize,probe,prone,proof,prose,proud,prune,pulse,pupil,
queen,query,quest,queue,quick,quiet,quota,quote,
radar,radio,raise,rally,range,rapid,ratio,reach,react,ready,realm,rebel,refer,reign,relax,remix,repay,repel,reply,retro,rider,ridge,rifle,rigid,risky,rival,river,robot,rocky,rodeo,rouge,rough,round,route,ruler,rural,rusty,
sadly,saint,sauce,scale,scene,score,scout,seize,sense,serve,setup,seven,shaft,shake,shall,shame,shape,share,shark,sharp,shelf,shell,shift,shine,shirt,shock,shore,short,shout,sight,since,sixth,sixty,skill,skull,slate,slave,sleep,slice,slide,slope,smart,smell,smile,smoke,snake,solar,solve,south,space,spare,spark,speak,speed,spend,spine,spite,split,spoke,spoon,squad,stage,stake,stale,stalk,stand,stark,start,state,steal,steam,steel,steep,steer,stern,stick,stiff,still,stock,stone,store,storm,story,stove,strap,stray,strip,study,style,suite,super,surge,swamp,swear,sweep,sweet,swift,sword,
table,taken,taste,teach,teeth,tense,tenth,terms,theft,theme,there,thick,thing,think,third,thorn,three,threw,throw,thumb,tiger,tight,timer,tired,title,today,token,torch,total,touch,tough,trace,track,trade,trail,train,trait,tramp,trash,trial,tribe,trick,tried,troop,truck,trump,trunk,trust,truth,tumor,tuned,tweak,twice,twist,typed,
ulcer,ultra,uncle,under,unify,union,unite,unity,until,upper,upset,urban,usage,usher,usual,
valve,value,venue,video,vigor,viral,virus,vital,vocal,vodka,voice,voter,vague,waste,watch,water,weave,weird,whole,wider,widow,windy,witch,world,worry,worse,worst,would,wound,woven,write,wrong,
yacht,yearn,yield,young,youth,
zebra,zesty,zones
]]

for word in raw:gmatch("[a-z]+") do
    if #word >= 3 then W[word] = true end
end

return W
